name: Daily Love Reminder

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 时间每天 0 点（对应北京时间 8 点）
  workflow_dispatch:     # 允许手动触发

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 3   # 超时保护

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 匹配你的开发环境

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 schedule

    - name: Execute Reminder Script
      run: python guo.py
