name: Triple Daily Reminders

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 0点（北京时间8点）
    # - cron: '*/5 * * * *'  # 测试用：每5分钟触发
  workflow_dispatch:

jobs:
  guo-reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4 schedule
      - run: python guo.py

  baozi-reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4 schedule
      - run: python pj2.py

  run-reminder:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4 schedule
      - run: python run.py
